### ISSUE TITLE
Decent homepage

### ISSUE THREAD

**Issue by lol768** [korobi/Web#28]
![](https://camo.githubusercontent.com/2d6a1f5349218a1a9f7775790ca640dc8e9c2c82/68747470733a2f2f692e696d6775722e636f6d2f707243754277342e706e67)
## todo
- [x] feature text
- [x] replacement of hero unit with logs as discussed with @bendem
- [x] #21 (Searching) if mentioned on home page
- [x] decide: remove about box in favour of smaller feature-type boxes with more targeted info
- [x] network info for channels
- ~~AJAX recent activity updater maybe. + JS relative times would be a nice to have~~
- [x] comments from @Zarthus: https://dev.korobi.io/network/esper/channel/korobi/logs/2015/06/29/#L35-95,108-112
